version: "3"

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      - pb_hooks:/pb/pb_hooks
      - pb_public:/pb/public
      - pb_migrations:/pb/pb_migrations

volumes:
  pb_data:
  pb_hooks:
  pb_public:
  pb_migrations:
