version: "3"

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: prompt-techniques-generator
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
      - ./pb_public:/pb_public
      - ./pb_migrations:/pb_migrations
